// MAY Generated by the tool
// Specific your PIN map here

#include "cpp/MCU/ST/STM32F1"
using namespace uni;

GPIO_Pin& LEDR = GPIO['B'][ 5];
GPIO_Pin& LEDG = GPIO['B'][ 0];
GPIO_Pin& LEDB = GPIO['B'][ 1];
GPIO_Pin& KEY1 = GPIO['A'][ 0];
GPIO_Pin& KEY2 = GPIO['C'][13];
