
c:
	gcc c.c -I$(uincpath) -D_DEBUG -L$(ubinpath) -lw32d -IE:/PROJ/SVGN/_inc -LE:/PROJ/SVGN/_oth -leasyx32 -oc.exe

cxx:
	g++ c.cpp ./cxxlib/* -I$(uincpath) -I$(uincpath)/cpp/Witch -D_DEBUG -L$(uincpath) -lw32d -IE:/PROJ/SVGN/_inc -LE:/PROJ/SVGN/_oth -leasyx32 -ox.exe
	

