[package]
name = "uni_crate_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unisym = { path = "/mnt/hgfs/unisym/lib/Rust/unisym" } #! change the path to fit the dev-env
